name: assetInventory
channels:
  - conda-forge
dependencies:
  - cfunits==3.2.9
  - erddapy
  - fiona
  - geopandas
  - jupyter
  - matplotlib
  - netcdf4
  - openpyxl
  - pandas
  - python=3.8
  - xarray
  - xlrd